<a href="https://colab.research.google.com/github/KorrawanOu/BSC_DPDM23/blob/main/Frequent_Patterns_(Association_Rules).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/My Drive/bsc_dpdm23_data'

Mounted at /content/drive

In [ ]:
data = pd.read_csv(os.path.join(path,'/content/drive/MyDrive/BSC_DRDM23/reduced_marketbasket.csv'),encoding='latin-1')

In [ ]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France

#Quiz ข้อมูลมากี่ประเภท

In [ ]:
data['Country'].describe()

count             541909
unique                38
top       United Kingdom
freq              495478
Name: Country, dtype: object

In [ ]:
set(data['Country'])

{'Australia',
 'Austria',
 'Bahrain',
 'Belgium',
 'Brazil',
 'Canada',
 'Channel Islands',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'EIRE',
 'European Community',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hong Kong',
 'Iceland',
 'Israel',
 'Italy',
 'Japan',
 'Lebanon',
 'Lithuania',
 'Malta',
 'Netherlands',
 'Norway',
 'Poland',
 'Portugal',
 'RSA',
 'Saudi Arabia',
 'Singapore',
 'Spain',
 'Sweden',
 'Switzerland',
 'USA',
 'United Arab Emirates',
 'United Kingdom',
 'Unspecified'}

#แปลง data ให้อยู่ในรูป transaction data ด้วย groupby.apply(list)

In [ ]:
data.groupby('InvoiceNo')['StockCode'].apply(list)

InvoiceNo
536365     [85123A, 71053, 84406B, 84029G, 84029E, 22752,...
536366                                        [22633, 22632]
536367     [84879, 22745, 22748, 22749, 22310, 84969, 226...
536368                          [22960, 22913, 22912, 22914]
536369                                               [21756]
                                 ...
C581484                                              [23843]
C581490                                       [22178, 23144]
C581499                                                  [M]
C581568                                              [21258]
C581569                                       [84978, 20979]
Name: StockCode, Length: 25900, dtype: object

In [ ]:
transactions = data.groupby('InvoiceNo')['StockCode'].apply(list)

## Association Rules

In [ ]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=774fb50a3bb79f41515244139bab5de3bbfe63a68579227c52686c13dc997024
  Stored in directory: /root/.cache/pip/wheels/c4/1a/79/20f55c470a50bb3702a8cb7c94d8ada15573538c7f4baebe2d
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
from apyori import apriori

In [ ]:
list(apriori(transactions,min_sup = 0.1))

[]

In [ ]:
frequentItemsets = list(apriori(transactions,min_support = 0.065))
frequentItemsets

[RelationRecord(items=frozenset({'22423'}), support=0.08386100386100385, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22423'}), confidence=0.08386100386100385, lift=1.0)]),
 RelationRecord(items=frozenset({'47566'}), support=0.06586872586872587, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'47566'}), confidence=0.06586872586872587, lift=1.0)]),
 RelationRecord(items=frozenset({'85099B'}), support=0.08243243243243244, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85099B'}), confidence=0.08243243243243244, lift=1.0)]),
 RelationRecord(items=frozenset({'85123A'}), support=0.08671814671814672, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85123A'}), confidence=0.08671814671814672, lift=1.0)])]

In [ ]:
len(frequentItemsets)

4

In [ ]:
frequentItemsets[0]

RelationRecord(items=frozenset({'22423'}), support=0.08386100386100385, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22423'}), confidence=0.08386100386100385, lift=1.0)])

In [ ]:
frequentItemsets[0][0]

frozenset({'22423'})

In [ ]:
dir(frequentItemsets[0][0])

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'copy',
 'difference',
 'intersection',
 'isdisjoint',
 'issubset',
 'issuperset',
 'symmetric_difference',
 'union']

In [ ]:
frequentItemsets[0][0].__len__()

1

In [ ]:
min_sup = 0.03

frequentItemsets = list(apriori(transactions,min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({'85099B', '22386'}), support=0.03216216216216216, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85099B', '22386'}), confidence=0.03216216216216216, lift=1.0), OrderedStatistic(items_base=frozenset({'22386'}), items_add=frozenset({'85099B'}), confidence=0.6766856214459789, lift=8.20897311262335), OrderedStatistic(items_base=frozenset({'85099B'}), items_add=frozenset({'22386'}), confidence=0.39016393442622943, lift=8.20897311262335)])
yes
RelationRecord(items=frozenset({'22697', '22699'}), support=0.03027027027027027, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22697', '22699'}), confidence=0.03027027027027027, lift=1.0), OrderedStatistic(items_base=frozenset({'22697'}), items_add=frozenset({'22699'}), confidence=0.7417218543046358, lift=17.1523178807947), OrderedStatistic(items_base=frozenset({'22699'}), items_add=frozenset({'22697'}), confidence=0.7, lift=17.1523178807947)])

แยกบรรทัด

RelationRecord(items=frozenset({'22386', '85099B'}),

support=0.03216216216216216,

ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22386', '85099B'}), confidence=0.03216216216216216, lift=1.0),

OrderedStatistic(items_base=frozenset({'22386'}), items_add=frozenset({'85099B'}), confidence=0.6766856214459789, lift=8.20897311262335),

OrderedStatistic(items_base=frozenset({'85099B'}), items_add=frozenset({'22386'}), confidence=0.39016393442622943, lift=8.20897311262335)])

In [ ]:
set(data[(data['StockCode']=='22386') | (data['StockCode']=='85099B') | (data['StockCode']=='22699') | (data['StockCode']=='22697') ]['Description'])

{'GREEN REGENCY TEACUP AND SAUCER',
 'JUMBO BAG PINK POLKADOT',
 'JUMBO BAG RED RETROSPOT',
 'ROSES REGENCY TEACUP AND SAUCER '}

##Quiz 22386 และ 85099ฺB คือสินค้าอะไร

In [ ]:
data[(data['StockCode']=='22386') | (data['StockCode']=='85099B')]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
86,536378,22386,JUMBO BAG PINK POLKADOT,10,12/01/2010 09:37,1.95,14688.0,United Kingdom
177,536386,85099B,JUMBO BAG RED RETROSPOT,100,12/01/2010 09:57,1.65,16029.0,United Kingdom
234,536390,85099B,JUMBO BAG RED RETROSPOT,100,12/01/2010 10:19,1.65,17511.0,United Kingdom
533,536409,85099B,JUMBO BAG RED RETROSPOT,2,12/01/2010 11:45,1.95,17908.0,United Kingdom
789,536464,22386,JUMBO BAG PINK POLKADOT,1,12/01/2010 12:23,1.95,17968.0,United Kingdom
...,...,...,...,...,...,...,...,...
539585,581439,22386,JUMBO BAG PINK POLKADOT,2,12/08/2011 16:30,4.13,NaN,United Kingdom
540434,581486,85099B,JUMBO BAG RED RETROSPOT,10,12/09/2011 09:38,2.08,17001.0,United Kingdom
541421,581498,22386,JUMBO BAG PINK POLKADOT,1,12/09/2011 10:26,4.13,NaN,United Kingdom
541536,581498,85099B,JUMBO BAG RED RETROSPOT,5,12/09/2011 10:26,4.13,NaN,United Kingdom
541806,581579,22386,JUMBO BAG PINK POLKADOT,10,12/09/2011 12:19,1.79,17581.0,United Kingdom

In [ ]:
set(data[(data['StockCode']=='22386') ]['Description'])

{'JUMBO BAG PINK POLKADOT'}

In [ ]:
set(data[(data['StockCode']=='85099B') ]['Description'])

{'JUMBO BAG RED RETROSPOT'}

RelationRecord(items=frozenset({'22699', '22697'}), support=0.03027027027027027,

ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22699', '22697'}), confidence=0.03027027027027027, lift=1.0),

OrderedStatistic(items_base=frozenset({'22697'}), items_add=frozenset({'22699'}), confidence=0.7417218543046358, lift=17.1523178807947),

OrderedStatistic(items_base=frozenset({'22699'}), items_add=frozenset({'22697'}), confidence=0.7, lift=17.1523178807947)])

In [ ]:
set(data[(data['StockCode']=='22699') | (data['StockCode']=='22697')]['InvoiceNo'])

{'555400',
 '537378',
 '536544',
 '577071',
 '555477',
 '541584',
 '558777',
 '565396',
 '567663',
 '572229',
 '563613',
 '577691',
 'C556880',
 '562950',
 'C554330',
 '550638',
 '556205',
 '567341',
 '580053',
 '565748',
 '539450',
 '547386',
 '567886',
 '570720',
 '581498',
 '563896',
 '561095',
 '560777',
 '544301',
 '546007',
 '545216',
 '581006',
 '562573',
 '553162',
 '560357',
 '577512',
 '552315',
 '549524',
 '573576',
 '569918',
 '561714',
 '537666',
 '547387',
 '577076',
 '554921',
 '541866',
 '564820',
 '539739',
 '549305',
 '547828',
 '552533',
 '571061',
 '562365',
 '558030',
 '546008',
 '561933',
 '566124',
 '546096',
 '562033',
 '554139',
 '570465',
 '568988',
 '538071',
 '561371',
 '546992',
 '552302',
 '572552',
 '569415',
 '575484',
 'C541693',
 '575846',
 '557301',
 '558862',
 '555106',
 '556826',
 '567507',
 '557672',
 '540662',
 '552867',
 '561217',
 '537335',
 '542632',
 '563166',
 '550968',
 '541110',
 '552816',
 '547107',
 '543467',
 '550987',
 '560976',
 '553671',
 '558873',
 '577298',
 '575703',
 '579539',
 '558089',
 '576381',
 '565120',
 '570227',
 '564837',
 '570597',
 '566326',
 '543626',
 '572092',
 '554704',
 '559800',
 '546113',
 '541709',
 '559493',
 '548559',
 '557259',
 '558918',
 '540005',
 '566607',
 '563505',
 '553210',
 '569570',
 '555499',
 '564972',
 '545543',
 '577078',
 '570127',
 '556264',
 '567922',
 '541219',
 '544940',
 '554039',
 '558315',
 '540464',
 '541280',
 '568676',
 '558702',
 '549192',
 '576339',
 '542221',
 '552857',
 '541506',
 '537738',
 '545526',
 '550500',
 '551775',
 '543909',
 '575866',
 '544657',
 '546314',
 '566976',
 '579445',
 'C543633',
 '542590',
 '544812',
 '562770',
 '553942',
 '574950',
 '567873',
 '556501',
 '571546',
 '579751',
 '550333',
 '565849',
 '550186',
 '566603',
 '539708',
 '562607',
 '563910',
 '553901',
 '560895',
 '558066',
 '572897',
 '550183',
 '542717',
 '545759',
 '550470',
 '561633',
 '551286',
 '565862',
 '546927',
 '579503',
 '570688',
 '545701',
 '558119',
 '550986',
 '542729',
 '581439',
 '562849',
 '576388',
 '565214',
 '559923',
 '579012',
 '547830',
 '544186',
 'C567358',
 '580367',
 '569419',
 'C548485',
 '579512',
 '543045',
 '556323',
 '548860',
 '549425',
 '553013',
 'C539071',
 '560504',
 '553575',
 '538951',
 '562166',
 '567793',
 '542619',
 'C569114',
 '564300',
 '548718',
 '565231',
 '545475',
 '555743',
 '545721',
 '569230',
 '550499',
 '550438',
 '556416',
 '547580',
 '546367',
 '538883',
 '549360',
 '555275',
 '552694',
 '564835',
 '578331',
 '578044',
 '568804',
 '551014',
 '575206',
 '536862',
 '547397',
 '571241',
 '542647',
 '578031',
 '570824',
 'C550664',
 '564432',
 '545445',
 '544768',
 '568199',
 '540539',
 'C561232',
 '570086',
 '555488',
 '571797',
 '563169',
 'C542263',
 '556095',
 '572549',
 '544421',
 '548516',
 '548163',
 '553462',
 '544887',
 '537642',
 '575742',
 '539465',
 'C542413',
 '568655',
 '570187',
 '548003',
 '564758',
 '576255',
 '565675',
 '571713',
 'C578144',
 '561631',
 '553461',
 '553709',
 '561891',
 '561894',
 'C562119',
 '539437',
 '561209',
 '537534',
 '544668',
 '540364',
 'C562921',
 '547788',
 'C551465',
 '546545',
 '565056',
 '551173',
 '571714',
 '550953',
 '568060',
 '550958',
 '561125',
 '544837',
 '574700',
 '549294',
 '566396',
 '544075',
 '571058',
 '578347',
 '540259',
 '555109',
 '544928',
 '545568',
 '554842',
 '545464',
 '562264',
 '573580',
 '548733',
 'C537834',
 '566255',
 '545154',
 '559639',
 '558259',
 '559497',
 '554935',
 '566395',
 '573553',
 '572028',
 '556237',
 '560790',
 'C545456',
 '577531',
 '547841',
 '558923',
 '573892',
 '556813',
 '551088',
 '552149',
 '564857',
 '580173',
 '548734',
 '562608',
 '577316',
 '567280',
 '549909',
 '551174',
 '549999',
 '537887',
 '536627',
 '548194',
 '555015',
 '560209',
 '553191',
 '576616',
 '562534',
 '572758',
 'C549840',
 '553202',
 '543923',
 '546915',
 '538903',
 '568048',
 '575324',
 '568908',
 '565117',
 'C572410',
 '577355',
 '552557',
 '542600',
 '538851',
 '574893',
 '579777',
 '548987',
 '545428',
 '551994',
 '562102',
 '564306',
 '563193',
 '577518',
 '552663',
 '556206',
 '564552',
 '581023',
 '546980',
 '550251',
 '581472',
 '548333',
 '580673',
 '564541',
 '561926',
 '554514',
 '553870',
 '572751',
 '544767',
 '544434',
 '558526',
 '555848',
 '551160',
 '559052',
 '557145',
 '537240',
 '559134',
 'C562375',
 '562717',
 '564057',
 '548158',
 '561637',
 '541592',
 '547846',
 '541132',
 '566583',
 '557500',
 '544888',
 '570677',
 '555630',
 '555836',
 '544893',
 '558770',
 '556459',
 '571283',
 '544205',
 '558475',
 '559906',
 '567368',
 '567671',
 '568333',
 '544749',
 '552734',
 'C577752',
 '563931',
 '576202',
 'C559949',
 '565726',
 '536804',
 '569493',
 '549852',
 '554158',
 '544681',
 '554372',
 '544055',
 '575607',
 '555722',
 '554124',
 '554013',
 '581122',
 '577400',
 '567639',
 '550307',
 '556636',
 '578344',
 '542719',
 '577610',
 '547360',
 '565151',
 '561355',
 '562955',
 '553543',
 '559942',
 '554040',
 '551550',
 '552678',
 '559941',
 '542881',
 '553661',
 '538177',
 '557616',
 '549295',
 '566985',
 '550265',
 '577358',
 '560580',
 '545410',
 '541129',
 '579572',
 '571937',
 '549296',
 '561394',
 '551960',
 '550471',
 '554036',
 '560246',
 '552259',
 '566221',
 '547826',
 '560773',
 '576063',
 '553768',
 '569737',
 'C562953',
 '555276',
 '536980',
 '556812',
 '560451',
 '579927',
 '575875',
 '544677',
 'C562147',
 '555524',
 '558372',
 '580669',
 '565917',
 '556783',
 '557117',
 '556821',
 '562157',
 '540646',
 '540154',
 '543201',
 '548983',
 '559337',
 '542255',
 '578273',
 '543251',
 '576246',
 '547547',
 '555594',
 '568057',
 '547967',
 '555925',
 '551334',
 '544338',
 '544394',
 '545377',
 '556259',
 '580983',
 '562420',
 'C556644',
 '544596',
 '548919',
 '558683',
 '565234',
 '554326',
 '552449',
 '546884',
 '578994',
 '577319',
 '544684',
 '554974',
 '538524',
 '541421',
 '551599',
 '559693',
 'C538059',
 '546498',
 '545036',
 '545176',
 'C555598',
 '564091',
 '569202',
 '557502',
 '546643',
 '547493',
 '555871',
 '567670',
 '551564',
 '564092',
 '544664',
 '541220',
 '544565',
 '570872',
 '573266',
 '560604',
 '541960',
 '562374',
 '542543',
 '571931',
 '570650',
 '546688',
 '550503',
 'C566084',
 '539737',
 '554110',
 '544095',
 '543106',
 '554337',
 '568955',
 '548714',
 'C558312',
 '572035',
 '543985',
 '554798',
 'C555358',
 '562711',
 '543399',
 '567378',
 '564974',
 '537176',
 '557034',
 '577020',
 '561236',
 '555695',
 '566581',
 '536856',
 '549435',
 '553607',
 '537313',
 '563384',
 'C579945',
 '566600',
 '550302',
 '548260',
 '548192',
 '536524',
 '561798',
 '580727',
 '549056',
 '579093',
 '561455',
 '552804',
 '580730',
 '548514',
 '560826',
 '560634',
 'C548355',
 '576051',
 '574852',
 '558116',
 '561820',
 '539594',
 '549261',
 '559886',
 '545912',
 '567128',
 '542389',
 '550915',
 '555870',
 '573511',
 '540848',
 '540352',
 '537254',
 '546212',
 '550613',
 '569888',
 '542344',
 '569524',
 '554030',
 '554113',
 '566602',
 '565847',
 '566257',
 '550914',
 '563906',
 '543013',
 '558035',
 '556917',
 '544207',
 '548726',
 '545474',
 '559553',
 '555510',
 '578065',
 '546752',
 '573070',
 '545429',
 '552825',
 'C551511',
 '548663',
 '549951',
 '541859',
 '569650',
 '560236',
 '550201',
 '559930',
 '579938',
 '546891',
 '570834',
 '579196',
 '551860',
 '566170',
 '541969',
 '572969',
 '572613',
 '578993',
 '552324',
 '544206',
 '567293',
 '573083',
 '549595',
 '544913',
 '550125',
 '575138',
 '561698',
 '570700',
 '536623',
 '563951',
 '553899',
 '551340',
 '539492',
 '579471',
 '581238',
 '574088',
 '559817',
 '568792',
 '543099',
 '566236',
 '565784',
 '568193',
 '565150',
 '579518',
 '570713',
 '562553',
 '577594',
 '546669',
 '559938',
 '564172',
 '573020',
 '537688',
 '575947',
 '537645',
 '553535',
 '547248',
 '576181',
 '574368',
 '543602',
 '537638',
 '580098',
 '536865',
 '571560',
 '567905',
 '567157',
 '556073',
 '564723',
 '579102',
 '552563',
 '547498',
 '568654',
 '543732',
 '548210',
 '553946',
 '545215',
 'C558255',
 '539593',
 '545601',
 '552715',
 '541810',
 '543754',
 '547949',
 '569367',
 '553718',
 '543451',
 '539436',
 '546892',
 '563442',
 '564714',
 '558904',
 '540777',
 '563023',
 '562353',
 '559295',
 '559510',
 '541783',
 '537643',
 '569545',
 '567336',
 '553869',
 '557211',
 '564301',
 '570701',
 '573320',
 '569246',
 '559525',
 '545022',
 '559112',
 '548373',
 '562377',
 '544089',
 'C565848',
 'C545438',
 '565919',
 '562222',
 '544824',
 'C545828',
 '543826',
 '554098',
 '568553',
 '564817',
 '547936',
 '578354',
 '546888',
 '554054',
 '560291',
 '565838',
 '536946',
 '546896',
 '545214',
 '542583',
 '574298',
 '563614',
 '546660',
 '579267',
 '554958',
 '553387',
 '556256',
 '566788',
 '537435',
 '576837',
 '575932',
 'C555409',
 '564065',
 '544339',
 '572553',
 '565289',
 '566091',
 '558565',
 '557645',
 '537470',
 'C555254',
 '538660',
 '569374',
 '581135',
 '539587',
 '574334',
 '539434',
 '575221',
 '557605',
 '580115',
 '548648',
 'C556268',
 '547712',
 '552710',
 '559055',
 '565331',
 '568567',
 'C545033',
 '558240',
 '563477',
 '546306',
 '545681',
 '548673',
 '549120',
 '581433',
 '561651',
 '545063',
 '565424',
 '572550',
 '576644',
 '546442',
 '573778',
 '536530',
 '553541',
 '550989',
 '541999',
 '555327',
 '540418',
 '544660',
 '547385',
 '543629',
 'C569911',
 '574739',
 '580501',
 '572082',
 '570459',
 'C577388',
 '566290',
 '570388',
 '579694',
 '554813',
 '543097',
 '554694',
 '539451',
 '541423',
 '558885',
 '543565',
 '543036',
 '563909',
 '565223',
 '554483',
 '559557',
 '567673',
 '540372',
 '551387',
 '537823',
 '566624',
 '554643',
 '545333',
 '575063',
 '540465',
 '551850',
 '539468',
 '559491',
 '557064',
 '560772',
 '558103',
 '543989',
 '566094',
 '553891',
 '553684',
 'C542912',
 '549124',
 '564754',
 '545320',
 '546683',
 '543485',
 '577618',
 '554028',
 '564755',
 '544574',
 '571550',
 '579297',
 '542349',
 '539738',
 '570428',
 '552231',
 '569834',
 '555486',
 '559878',
 '575477',
 '553146',
 '577500',
 '537434',
 '580667',
 '552514',
 '550468',
 '538148',
 'C552016',
 'C564964',
 '562273',
 '575490',
 '547399',
 '560590',
 '553612',
 '553546',
 '568411',
 'C550648',
 '580665',
 '543660',
 '545014',
 '545032',
 '552642',
 '550899',
 '553385',
 '566572',
 '543486',
 '558540',
 'C574507',
 '551944',
 '551995',
 '565724',
 '564191',
 '573125',
 '542102',
 '563561',
 '557481',
 '544778',
 '545020',
 '538880',
 '543370',
 '566988',
 '562933',
 '545945',
 '566482',
 '566731',
 '572274',
 '545078',
 '552665',
 '569568',
 '564838',
 '557621',
 '545467',
 '543487',
 '569137',
 '567324',
 '537385',
 '580066',
 '557350',
 '551825',
 '550978',
 '561329',
 '563922',
 '555522',
 '575939',
 '541576',
 '566477',
 '566871',
 '551352',
 '577258',
 '543116',
 '543277',
 '543973',
 'C544665',
 '559827',
 '556577',
 '536624',
 '573388',
 '581059',
 '538566',
 '550519',
 '571433',
 '552270',
 '578314',
 '550210',
 'C552698',
 '550314',
 '572854',
 '551657',
 '561051',
 '551885',
 '547206',
 '549016',
 '552247',
 '540839',
 '563353',
 '566559',
 '545340',
 '570488',
 '539442',
 '575946',
 'C556793',
 '571305',
 '581495',
 '564221',
 '573338',
 '551414',
 ...}

In [ ]:
data[data['InvoiceNo']=='562950']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
297488,562950,22752,SET 7 BABUSHKA NESTING BOXES,2,08/11/2011 09:56,8.50,15608.0,United Kingdom
297489,562950,22755,SMALL PURPLE BABUSHKA NOTEBOOK,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297490,562950,22753,SMALL YELLOW BABUSHKA NOTEBOOK,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297491,562950,22754,SMALL RED BABUSHKA NOTEBOOK,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297492,562950,22757,LARGE RED BABUSHKA NOTEBOOK,12,08/11/2011 09:56,1.25,15608.0,United Kingdom
297493,562950,22758,LARGE PURPLE BABUSHKA NOTEBOOK,12,08/11/2011 09:56,1.25,15608.0,United Kingdom
297494,562950,22756,LARGE YELLOW BABUSHKA NOTEBOOK,12,08/11/2011 09:56,1.25,15608.0,United Kingdom
297495,562950,23310,BUBBLEGUM RING ASSORTED,36,08/11/2011 09:56,0.42,15608.0,United Kingdom
297496,562950,23280,FOLDING BUTTERFLY MIRROR HOT PINK,12,08/11/2011 09:56,0.83,15608.0,United Kingdom
297497,562950,22383,LUNCH BAG SUKI DESIGN,10,08/11/2011 09:56,1.65,15608.0,United Kingdom
297498,562950,22492,MINI PAINT SET VINTAGE,36,08/11/2011 09:56,0.65,15608.0,United Kingdom
297499,562950,71459,HANGING JAM JAR T-LIGHT HOLDER,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297500,562950,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297501,562950,21175,GIN + TONIC DIET METAL SIGN,12,08/11/2011 09:56,2.55,15608.0,United Kingdom
297502,562950,23164,REGENCY CAKE SLICE,4,08/11/2011 09:56,4.95,15608.0,United Kingdom
297503,562950,23245,SET OF 3 REGENCY CAKE TINS,4,08/11/2011 09:56,4.95,15608.0,United Kingdom
297504,562950,23171,REGENCY TEA PLATE GREEN,12,08/11/2011 09:56,1.65,15608.0,United Kingdom
297505,562950,22697,GREEN REGENCY TEACUP AND SAUCER,6,08/11/2011 09:56,2.95,15608.0,United Kingdom

# HW 1 หา Frequent Item Set และ Association Rules


*   ของช่วงเวลา Chrismas & New Year (1 Dec-31 Dec)
*   ของในประเทศในยุโรป
*   ของช่วงเวลา ตรุษจีน ในทวีป Asia (15 Jan -15 Feb)
*   ของช่วงเวลา Chrismas & New Year ในทวีป Europe (1 Dec-31 Dec)
*   ของวันวาเลนไทน์
*   โดยจัดกลุ่มตามประเทศ + เดือน

In [ ]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France

In [ ]:
!pip install apyori

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Requirement already satisfied: apyori in /usr/local/lib/python3.10/dist-packages (1.1.2)

In [ ]:
from apyori import apriori

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
# Convert รูปแบบเวลาใน column InvoiceDate ให้อยู่ในรูปที่ต้องการ
data['InvoiceDate'] = pd.to_datetime(data['InvoiceDate'], format='%m/%d/%Y %H:%M')

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

## ข้อ 5

In [ ]:
# เลือกเฉพาะวันวาเลนไทน์
filtered_df5 = data[(data['InvoiceDate'].dt.month == 2) & (data['InvoiceDate'].dt.day == 14) ]

# โชว์ datafram เพื่อcheck
print(filtered_df5)

      InvoiceNo StockCode                         Description  Quantity  \
88847    543821     22926      IVORY GIANT GARDEN THERMOMETER         2
88848    543821     22928     YELLOW GIANT GARDEN THERMOMETER         2
88849    543821     22925       BLUE GIANT GARDEN THERMOMETER         2
88850    543821     85175               CACTI T-LIGHT CANDLES        16
88851    543821     22456     NATURAL SLATE CHALKBOARD LARGE          3
...         ...       ...                                 ...       ...
89950    543979     21889              WOODEN BOX OF DOMINOES         1
89951    543979     85176          SEWING SUSAN 21 NEEDLE SET         1
89952    543979     37446  MINI CAKE STAND WITH HANGING CAKES         1
89953    543979     21657     MILK BOTTLE WITH GLASS STOPPER          1
89954   C543980     22728           ALARM CLOCK BAKELIKE PINK        -1

              InvoiceDate  UnitPrice  CustomerID         Country
88847 2011-02-14 09:24:00       5.95     17667.0  United Kingdom
88848 2011-02-14 09:24:00       5.95     17667.0  United Kingdom
88849 2011-02-14 09:24:00       5.95     17667.0  United Kingdom
88850 2011-02-14 09:24:00       0.42     17667.0  United Kingdom
88851 2011-02-14 09:24:00       4.95     17667.0  United Kingdom
...                   ...        ...         ...             ...
89950 2011-02-14 15:43:00       1.25     14606.0  United Kingdom
89951 2011-02-14 15:43:00       0.85     14606.0  United Kingdom
89952 2011-02-14 15:43:00       1.45     14606.0  United Kingdom
89953 2011-02-14 15:43:00       6.95     14606.0  United Kingdom
89954 2011-02-14 16:39:00       3.75     14189.0  United Kingdom

[1108 rows x 8 columns]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
transactions5 = filtered_df5.groupby('InvoiceNo')['Description'].apply(list).reset_index() #ทำการ group และทำให้ข้อมูลใน Description เป็นlist
transactions_apply5 = transactions5['Description'].apply(lambda x: [str(item) for item in x]) #ใช้ฟังก์ชัน lambda เพื่อแปลงสินค้าทุกชิ้นใน list ของ 'transactions' เป็นข้อความ (string)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
frequentItemset5 = list(apriori(transactions_apply5, min_support=0.035))

for record in frequentItemset5:
    if len(record.items) > 1:
        print('yes')
        print(f"Items: {', '.join(record.items)}")
        print(f"Support: {record.support:.4f} ({record.support*100:.2f}%)")

        for i, stat in enumerate(record.ordered_statistics, 1):
            items_base = 'None' if not stat.items_base else ', '.join(stat.items_base)
            items_add = ', '.join(stat.items_add)
            confidence = stat.confidence
            lift = stat.lift

            print(f"Rule {i}: ({items_base} -> {items_add} : Confidence={confidence:.4f}, Lift={lift:.4f})")
        print()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
min_sup = 0.09
frequentItemsets5= list(apriori(transactions_apply5,min_support = min_sup))
for i in frequentItemsets_va:
    if i[0].__len__()>1:
        print('yes')
        print(i)